//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_RoomCardAllSorce
    {
        public int riqi { get; set; }
        public long RoomCardNum { get; set; }
        public int RoomCardType { get; set; }
        public int CreateUserID { get; set; }
        public Nullable<int> RoomPayType { get; set; }
        public int GameID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> DeskID { get; set; }
        public Nullable<int> UserID1 { get; set; }
        public Nullable<int> UserID2 { get; set; }
        public Nullable<int> UserID3 { get; set; }
        public Nullable<int> UserID4 { get; set; }
        public Nullable<int> UserID5 { get; set; }
        public Nullable<int> UserID6 { get; set; }
        public string NickName1 { get; set; }
        public string NickName2 { get; set; }
        public string NickName3 { get; set; }
        public string NickName4 { get; set; }
        public string NickName5 { get; set; }
        public string NickName6 { get; set; }
        public Nullable<int> UserFen1 { get; set; }
        public Nullable<int> UserFen2 { get; set; }
        public Nullable<int> UserFen3 { get; set; }
        public Nullable<int> UserFen4 { get; set; }
        public Nullable<int> UserFen5 { get; set; }
        public Nullable<int> UserFen6 { get; set; }
        public Nullable<int> UserWin1 { get; set; }
        public Nullable<int> UserWin2 { get; set; }
        public Nullable<int> UserWin3 { get; set; }
        public Nullable<int> UserWin4 { get; set; }
        public Nullable<int> UserWin5 { get; set; }
        public Nullable<int> UserWin6 { get; set; }
        public Nullable<int> UserDian1 { get; set; }
        public Nullable<int> UserDian2 { get; set; }
        public Nullable<int> UserDian3 { get; set; }
        public Nullable<int> UserDian4 { get; set; }
        public Nullable<int> UserDian5 { get; set; }
        public Nullable<int> UserDian6 { get; set; }
        public Nullable<int> iGameRule { get; set; }
        public Nullable<int> Quan { get; set; }
        public Nullable<int> JuShu { get; set; }
        public Nullable<int> iDifen { get; set; }
        public Nullable<int> iQunNum { get; set; }
        public Nullable<int> iUseIngot { get; set; }
        public Nullable<int> iUseMoney { get; set; }
        public string CreateNickName { get; set; }
        public Nullable<int> iRoomStatue { get; set; }
        public Nullable<int> iFinishTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> iPlaying { get; set; }
    }
}
