//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_BiSaiInfo
    {
        public int UserID { get; set; }
        public int BiSaiType { get; set; }
        public int AllJiFen { get; set; }
        public int TodayJiFen { get; set; }
        public int DuiJuJiFen { get; set; }
        public int ShareJiFen { get; set; }
        public int NowJuShu { get; set; }
        public int MaxJuShu { get; set; }
        public Nullable<System.DateTime> ShareTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
