//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_xitong
    {
        public int riqi { get; set; }
        public long usermoney { get; set; }
        public long chongzhi { get; set; }
        public long diankachongzhi { get; set; }
        public long shuying { get; set; }
        public long zhuanzhuang { get; set; }
        public long zengsong { get; set; }
        public long taxes { get; set; }
        public long shouxufei { get; set; }
        public long qita { get; set; }
        public int zhuceshu { get; set; }
        public int denglushu { get; set; }
        public int zuigaozaixian { get; set; }
        public int pingjunzaixian { get; set; }
        public System.DateTime updatetime { get; set; }
    }
}
