//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_MatchBaseInfo
    {
        public int MathID { get; set; }
        public int MathType { get; set; }
        public int GameID { get; set; }
        public int RoomID { get; set; }
        public string MathName { get; set; }
        public int MinJuShu { get; set; }
        public int MaxJuShu { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> MathPay { get; set; }
        public Nullable<int> Statue { get; set; }
        public Nullable<int> Award0 { get; set; }
        public Nullable<int> Award1 { get; set; }
        public Nullable<int> Award2 { get; set; }
        public Nullable<int> Award3 { get; set; }
        public Nullable<int> Award4 { get; set; }
        public Nullable<int> Award5 { get; set; }
        public Nullable<int> Award6 { get; set; }
        public Nullable<int> Award7 { get; set; }
        public Nullable<int> Award8 { get; set; }
        public Nullable<int> Award9 { get; set; }
        public Nullable<int> SignUpCount { get; set; }
        public Nullable<int> MatchNumber { get; set; }
        public Nullable<int> AwardCount { get; set; }
        public Nullable<int> AllPay { get; set; }
        public Nullable<int> AllTax { get; set; }
        public Nullable<int> AllAward { get; set; }
        public string RuleDescribe { get; set; }
        public string AwardDescribe { get; set; }
        public Nullable<int> NowPay { get; set; }
    }
}
