//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_RoomCardQunBase
    {
        public int riqi { get; set; }
        public int iQunNum { get; set; }
        public string QunName { get; set; }
        public int CreateUserID { get; set; }
        public string CreateUserName { get; set; }
        public int iRoomCount { get; set; }
        public Nullable<int> iMaxMemberCount { get; set; }
        public int MemberCount { get; set; }
        public Nullable<int> OpenRoomCondition { get; set; }
        public Nullable<int> AddMemberCondition { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> iUseIngot { get; set; }
        public Nullable<int> iUseMoney { get; set; }
        public Nullable<int> iPlayCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string GongGao { get; set; }
        public Nullable<int> iAllGameTax { get; set; }
        public Nullable<int> iQunZhuTax { get; set; }
    }
}
