//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_RoomWinCtrlLog
    {
        public int LogId { get; set; }
        public int Roomid { get; set; }
        public long AllNOte { get; set; }
        public long AllWin { get; set; }
        public long TodayNote { get; set; }
        public long TodayWin { get; set; }
        public int NowWinPercent { get; set; }
        public int WantWinPercent { get; set; }
        public System.DateTime updatetime { get; set; }
        public int PlayerCount { get; set; }
        public string RoomName { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
