//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_User_Win_Ctrl
    {
        public int userid { get; set; }
        public long usermoney { get; set; }
        public long todaywin { get; set; }
        public long chongzhi { get; set; }
        public long diankachongzhi { get; set; }
        public long zhuanru { get; set; }
        public long zhuanchu { get; set; }
        public long zhuanzhang { get; set; }
        public long shu { get; set; }
        public long ying { get; set; }
        public long shuying { get; set; }
        public long zengsong { get; set; }
        public long oldwin { get; set; }
        public int canwin { get; set; }
        public long allcanwin { get; set; }
        public int resultcount { get; set; }
        public string MathineCode { get; set; }
        public Nullable<System.DateTime> updtime { get; set; }
        public Nullable<long> zengsongIngot { get; set; }
        public Nullable<int> ctrlpercent { get; set; }
        public Nullable<int> iGameTax { get; set; }
        public Nullable<int> itodayGameTax { get; set; }
    }
}
