//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_RoomCardQunFriend
    {
        public int riqi { get; set; }
        public int iQunNum { get; set; }
        public int CreateUserID { get; set; }
        public int MemberUserID { get; set; }
        public string MemberUserName { get; set; }
        public string headimgurl { get; set; }
        public int IsAdmin { get; set; }
        public int CanOpenRoom { get; set; }
        public Nullable<int> iUseIngot { get; set; }
        public Nullable<int> iUseMoney { get; set; }
        public Nullable<int> iPlayCount { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
