//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_RoomCardGameRecord
    {
        public int riqi { get; set; }
        public long RoomCardNum { get; set; }
        public int RoomCardType { get; set; }
        public int CreateUserID { get; set; }
        public int GameID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> UserID1 { get; set; }
        public Nullable<int> UserID2 { get; set; }
        public Nullable<int> UserID3 { get; set; }
        public Nullable<int> UserID4 { get; set; }
        public Nullable<int> UserID5 { get; set; }
        public Nullable<int> UserID6 { get; set; }
        public string NickName1 { get; set; }
        public string NickName2 { get; set; }
        public string NickName3 { get; set; }
        public string NickName4 { get; set; }
        public string NickName5 { get; set; }
        public string NickName6 { get; set; }
        public Nullable<int> ChangeFen1 { get; set; }
        public Nullable<int> ChangeFen2 { get; set; }
        public Nullable<int> ChangeFen3 { get; set; }
        public Nullable<int> ChangeFen4 { get; set; }
        public Nullable<int> ChangeFen5 { get; set; }
        public Nullable<int> ChangeFen6 { get; set; }
        public Nullable<int> WinUser { get; set; }
        public Nullable<int> DianUser { get; set; }
        public Nullable<int> iHuTypeRule { get; set; }
        public Nullable<int> Quan { get; set; }
        public Nullable<int> iUseMoney { get; set; }
        public Nullable<int> JuShu { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> GameTime { get; set; }
    }
}
