//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_T_youxi
    {
        public int riqi { get; set; }
        public int gamenameid { get; set; }
        public long yingkui { get; set; }
        public int renshu { get; set; }
        public System.DateTime updatetime { get; set; }
    }
}
