//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class moerDataEntities : DbContext
    {
        public moerDataEntities()
            : base("name=moerDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A_T_GoodNumber> A_T_GoodNumber { get; set; }
        public virtual DbSet<A_T_RoomWinCtrl> A_T_RoomWinCtrl { get; set; }
        public virtual DbSet<A_T_RoomWinCtrlLog> A_T_RoomWinCtrlLog { get; set; }
        public virtual DbSet<A_T_SysNews> A_T_SysNews { get; set; }
        public virtual DbSet<A_T_User_Win_Ctrl> A_T_User_Win_Ctrl { get; set; }
        public virtual DbSet<A_T_xitong> A_T_xitong { get; set; }
        public virtual DbSet<A_T_youxi> A_T_youxi { get; set; }
        public virtual DbSet<A_T_youxi_fangjian> A_T_youxi_fangjian { get; set; }
        public virtual DbSet<qian_dao> qian_dao { get; set; }
        public virtual DbSet<Sys_ProcErrorCollection> Sys_ProcErrorCollection { get; set; }
        public virtual DbSet<tab_SendSMS> tab_SendSMS { get; set; }
        public virtual DbSet<TBankDeposit> TBankDeposit { get; set; }
        public virtual DbSet<TBattleRoomInfo> TBattleRoomInfo { get; set; }
        public virtual DbSet<TChangeRecord> TChangeRecord { get; set; }
        public virtual DbSet<TChangeRecordUser> TChangeRecordUser { get; set; }
        public virtual DbSet<TCharmExchange> TCharmExchange { get; set; }
        public virtual DbSet<TContestInfo> TContestInfo { get; set; }
        public virtual DbSet<TFasciChangeRecord> TFasciChangeRecord { get; set; }
        public virtual DbSet<TGameKindInfo> TGameKindInfo { get; set; }
        public virtual DbSet<TGameNameInfo> TGameNameInfo { get; set; }
        public virtual DbSet<TGameRoomBase> TGameRoomBase { get; set; }
        public virtual DbSet<TGameRoomInfo> TGameRoomInfo { get; set; }
        public virtual DbSet<TGameRoomMsg> TGameRoomMsg { get; set; }
        public virtual DbSet<TGameRoomTable> TGameRoomTable { get; set; }
        public virtual DbSet<TGM_AwardType> TGM_AwardType { get; set; }
        public virtual DbSet<TGM_OperationRecord> TGM_OperationRecord { get; set; }
        public virtual DbSet<TMatchTable> TMatchTable { get; set; }
        public virtual DbSet<TMoneyChangeRecord> TMoneyChangeRecord { get; set; }
        public virtual DbSet<TMoneyExceptLog> TMoneyExceptLog { get; set; }
        public virtual DbSet<TProp> TProp { get; set; }
        public virtual DbSet<TPropBuyGive> TPropBuyGive { get; set; }
        public virtual DbSet<TPropDefine> TPropDefine { get; set; }
        public virtual DbSet<TPropSale> TPropSale { get; set; }
        public virtual DbSet<TReceiveMoneyDefind> TReceiveMoneyDefind { get; set; }
        public virtual DbSet<TSendMoneyRecord> TSendMoneyRecord { get; set; }
        public virtual DbSet<TSendMoneyRecord_New> TSendMoneyRecord_New { get; set; }
        public virtual DbSet<TUserCallGM> TUserCallGM { get; set; }
        public virtual DbSet<TUserInfo> TUserInfo { get; set; }
        public virtual DbSet<TUserMoneyChange> TUserMoneyChange { get; set; }
        public virtual DbSet<TUsers> TUsers { get; set; }
        public virtual DbSet<TUserVip> TUserVip { get; set; }
        public virtual DbSet<Web_Activity> Web_Activity { get; set; }
        public virtual DbSet<Web_AdminEmail> Web_AdminEmail { get; set; }
        public virtual DbSet<Web_AdminModifyLog> Web_AdminModifyLog { get; set; }
        public virtual DbSet<Web_Agency> Web_Agency { get; set; }
        public virtual DbSet<Web_AgencyAccountLog> Web_AgencyAccountLog { get; set; }
        public virtual DbSet<Web_AgencyBalanceLog> Web_AgencyBalanceLog { get; set; }
        public virtual DbSet<Web_AgencyDayReport> Web_AgencyDayReport { get; set; }
        public virtual DbSet<Web_AgencyMoneyChangeLog> Web_AgencyMoneyChangeLog { get; set; }
        public virtual DbSet<Web_AgencyPercentChange> Web_AgencyPercentChange { get; set; }
        public virtual DbSet<Web_AgencyPopeSet> Web_AgencyPopeSet { get; set; }
        public virtual DbSet<Web_AgencyRMBCost> Web_AgencyRMBCost { get; set; }
        public virtual DbSet<Web_Agent> Web_Agent { get; set; }
        public virtual DbSet<Web_AgentPay> Web_AgentPay { get; set; }
        public virtual DbSet<Web_AgentRebate> Web_AgentRebate { get; set; }
        public virtual DbSet<Web_AgentUser> Web_AgentUser { get; set; }
        public virtual DbSet<Web_AlmsConfig> Web_AlmsConfig { get; set; }
        public virtual DbSet<Web_Analy_DateReport> Web_Analy_DateReport { get; set; }
        public virtual DbSet<Web_Analy_MonthReport> Web_Analy_MonthReport { get; set; }
        public virtual DbSet<Web_Analy_NewUserReport> Web_Analy_NewUserReport { get; set; }
        public virtual DbSet<Web_AnalyData_DateOnline> Web_AnalyData_DateOnline { get; set; }
        public virtual DbSet<Web_ApplyVipRoom> Web_ApplyVipRoom { get; set; }
        public virtual DbSet<Web_Artifact> Web_Artifact { get; set; }
        public virtual DbSet<Web_ArtifactLog> Web_ArtifactLog { get; set; }
        public virtual DbSet<Web_Award> Web_Award { get; set; }
        public virtual DbSet<Web_AwardLog> Web_AwardLog { get; set; }
        public virtual DbSet<Web_Card> Web_Card { get; set; }
        public virtual DbSet<Web_CharmExchangeLog> Web_CharmExchangeLog { get; set; }
        public virtual DbSet<Web_ClearFasciPropDefine> Web_ClearFasciPropDefine { get; set; }
        public virtual DbSet<Web_ClearFasciPropUseLog> Web_ClearFasciPropUseLog { get; set; }
        public virtual DbSet<Web_ClearingLog> Web_ClearingLog { get; set; }
        public virtual DbSet<Web_Clothes> Web_Clothes { get; set; }
        public virtual DbSet<Web_CompanyInfo> Web_CompanyInfo { get; set; }
        public virtual DbSet<Web_ContestRank> Web_ContestRank { get; set; }
        public virtual DbSet<Web_Count_AgencyOnline> Web_Count_AgencyOnline { get; set; }
        public virtual DbSet<Web_Count_OnlineUsers> Web_Count_OnlineUsers { get; set; }
        public virtual DbSet<Web_Count_RoomOnline> Web_Count_RoomOnline { get; set; }
        public virtual DbSet<Web_DataAnaly_Users> Web_DataAnaly_Users { get; set; }
        public virtual DbSet<Web_DataClearLog> Web_DataClearLog { get; set; }
        public virtual DbSet<Web_DayTaxReport> Web_DayTaxReport { get; set; }
        public virtual DbSet<Web_EveryoneBeSpread> Web_EveryoneBeSpread { get; set; }
        public virtual DbSet<Web_EveryoneSpread> Web_EveryoneSpread { get; set; }
        public virtual DbSet<Web_EveryoneSpreadRebate> Web_EveryoneSpreadRebate { get; set; }
        public virtual DbSet<Web_Exchange> Web_Exchange { get; set; }
        public virtual DbSet<Web_FasciExchangeConfig> Web_FasciExchangeConfig { get; set; }
        public virtual DbSet<Web_FasciExchangeLog> Web_FasciExchangeLog { get; set; }
        public virtual DbSet<Web_FengHao> Web_FengHao { get; set; }
        public virtual DbSet<Web_FriendLink> Web_FriendLink { get; set; }
        public virtual DbSet<Web_GameGuidList> Web_GameGuidList { get; set; }
        public virtual DbSet<Web_GameInfo> Web_GameInfo { get; set; }
        public virtual DbSet<Web_GameMain> Web_GameMain { get; set; }
        public virtual DbSet<Web_GameType> Web_GameType { get; set; }
        public virtual DbSet<Web_GUID> Web_GUID { get; set; }
        public virtual DbSet<Web_IndexFlash> Web_IndexFlash { get; set; }
        public virtual DbSet<web_IngotChangeGold> web_IngotChangeGold { get; set; }
        public virtual DbSet<Web_IngotChangeLog> Web_IngotChangeLog { get; set; }
        public virtual DbSet<Web_IngotTransLog> Web_IngotTransLog { get; set; }
        public virtual DbSet<Web_LotterAward> Web_LotterAward { get; set; }
        public virtual DbSet<Web_LotterConfig> Web_LotterConfig { get; set; }
        public virtual DbSet<Web_LotteriesLog> Web_LotteriesLog { get; set; }
        public virtual DbSet<Web_LotterLog> Web_LotterLog { get; set; }
        public virtual DbSet<Web_LotterSpecial> Web_LotterSpecial { get; set; }
        public virtual DbSet<Web_manage_admin> Web_manage_admin { get; set; }
        public virtual DbSet<Web_Manage_Model> Web_Manage_Model { get; set; }
        public virtual DbSet<Web_Manage_Permission> Web_Manage_Permission { get; set; }
        public virtual DbSet<Web_Manage_Popedom> Web_Manage_Popedom { get; set; }
        public virtual DbSet<Web_MatchAwardConfig> Web_MatchAwardConfig { get; set; }
        public virtual DbSet<Web_MatchSendType> Web_MatchSendType { get; set; }
        public virtual DbSet<Web_MoneyChangeLog> Web_MoneyChangeLog { get; set; }
        public virtual DbSet<Web_MoneyStatEveryday> Web_MoneyStatEveryday { get; set; }
        public virtual DbSet<Web_msg> Web_msg { get; set; }
        public virtual DbSet<Web_NewsData> Web_NewsData { get; set; }
        public virtual DbSet<Web_NewsType> Web_NewsType { get; set; }
        public virtual DbSet<Web_PConfig> Web_PConfig { get; set; }
        public virtual DbSet<Web_PlatWinLostDateReport> Web_PlatWinLostDateReport { get; set; }
        public virtual DbSet<Web_PlayerDayReport> Web_PlayerDayReport { get; set; }
        public virtual DbSet<Web_PointChangeLog> Web_PointChangeLog { get; set; }
        public virtual DbSet<Web_PropChangeLog> Web_PropChangeLog { get; set; }
        public virtual DbSet<Web_PVAndIPStat> Web_PVAndIPStat { get; set; }
        public virtual DbSet<Web_Red> Web_Red { get; set; }
        public virtual DbSet<Web_RedCashLog> Web_RedCashLog { get; set; }
        public virtual DbSet<Web_RedGiftLog> Web_RedGiftLog { get; set; }
        public virtual DbSet<Web_RedLog> Web_RedLog { get; set; }
        public virtual DbSet<Web_RMBCost> Web_RMBCost { get; set; }
        public virtual DbSet<Web_SendCode> Web_SendCode { get; set; }
        public virtual DbSet<Web_Share> Web_Share { get; set; }
        public virtual DbSet<Web_SMSLog> Web_SMSLog { get; set; }
        public virtual DbSet<Web_SpreadPartner> Web_SpreadPartner { get; set; }
        public virtual DbSet<Web_SpreadPartnerConfig> Web_SpreadPartnerConfig { get; set; }
        public virtual DbSet<Web_SpreadPartnerRecharge> Web_SpreadPartnerRecharge { get; set; }
        public virtual DbSet<Web_SpreadUserRecharge> Web_SpreadUserRecharge { get; set; }
        public virtual DbSet<Web_Statistic> Web_Statistic { get; set; }
        public virtual DbSet<Web_System> Web_System { get; set; }
        public virtual DbSet<Web_TaxStatEveryDay> Web_TaxStatEveryDay { get; set; }
        public virtual DbSet<Web_Tool_Action> Web_Tool_Action { get; set; }
        public virtual DbSet<Web_Tool_Admin> Web_Tool_Admin { get; set; }
        public virtual DbSet<Web_Tool_Group> Web_Tool_Group { get; set; }
        public virtual DbSet<Web_Tool_GroupPermit> Web_Tool_GroupPermit { get; set; }
        public virtual DbSet<Web_Tool_Module> Web_Tool_Module { get; set; }
        public virtual DbSet<Web_Tool_UserPermit> Web_Tool_UserPermit { get; set; }
        public virtual DbSet<Web_TransAssetLog> Web_TransAssetLog { get; set; }
        public virtual DbSet<Web_TransfersAccount> Web_TransfersAccount { get; set; }
        public virtual DbSet<Web_TransLog> Web_TransLog { get; set; }
        public virtual DbSet<Web_TuiGuang> Web_TuiGuang { get; set; }
        public virtual DbSet<Web_TuiGuangLog> Web_TuiGuangLog { get; set; }
        public virtual DbSet<Web_UserAlbum> Web_UserAlbum { get; set; }
        public virtual DbSet<Web_UserAlbumColumn> Web_UserAlbumColumn { get; set; }
        public virtual DbSet<Web_UserApplyVipRecord> Web_UserApplyVipRecord { get; set; }
        public virtual DbSet<Web_UserEmail> Web_UserEmail { get; set; }
        public virtual DbSet<Web_UserModifyLog> Web_UserModifyLog { get; set; }
        public virtual DbSet<Web_Users> Web_Users { get; set; }
        public virtual DbSet<A_T_BiSaiInfo> A_T_BiSaiInfo { get; set; }
        public virtual DbSet<A_T_MatchBaseInfo> A_T_MatchBaseInfo { get; set; }
        public virtual DbSet<A_T_MathRecord> A_T_MathRecord { get; set; }
        public virtual DbSet<A_T_MathUser> A_T_MathUser { get; set; }
        public virtual DbSet<A_T_RoomCardAllSorce> A_T_RoomCardAllSorce { get; set; }
        public virtual DbSet<A_T_RoomCardGameRecord> A_T_RoomCardGameRecord { get; set; }
        public virtual DbSet<A_T_RoomCardQunBase> A_T_RoomCardQunBase { get; set; }
        public virtual DbSet<A_T_RoomCardQunFriend> A_T_RoomCardQunFriend { get; set; }
        public virtual DbSet<A_T_RoomCardRecord> A_T_RoomCardRecord { get; set; }
        public virtual DbSet<TBankSerialRes> TBankSerialRes { get; set; }
        public virtual DbSet<TBankSerialResource> TBankSerialResource { get; set; }
        public virtual DbSet<TBankWallet> TBankWallet { get; set; }
        public virtual DbSet<TBattleMatchTable> TBattleMatchTable { get; set; }
        public virtual DbSet<TContestRecord> TContestRecord { get; set; }
        public virtual DbSet<TContestUserRecord> TContestUserRecord { get; set; }
        public virtual DbSet<tempempgame> tempempgame { get; set; }
        public virtual DbSet<TGameIPRule> TGameIPRule { get; set; }
        public virtual DbSet<TGameLock> TGameLock { get; set; }
        public virtual DbSet<TGameServerInfo> TGameServerInfo { get; set; }
        public virtual DbSet<TGiveIngotRecord> TGiveIngotRecord { get; set; }
        public virtual DbSet<TGMRecord> TGMRecord { get; set; }
        public virtual DbSet<TLockCode> TLockCode { get; set; }
        public virtual DbSet<TLoginRecord> TLoginRecord { get; set; }
        public virtual DbSet<TProc_Error_Log> TProc_Error_Log { get; set; }
        public virtual DbSet<TReceiveMoneyRecord> TReceiveMoneyRecord { get; set; }
        public virtual DbSet<TRoomIPRule> TRoomIPRule { get; set; }
        public virtual DbSet<TRoomRecord> TRoomRecord { get; set; }
        public virtual DbSet<TTransferRecord> TTransferRecord { get; set; }
        public virtual DbSet<TUserList> TUserList { get; set; }
        public virtual DbSet<TUserLoginGame> TUserLoginGame { get; set; }
        public virtual DbSet<TUserNameRule> TUserNameRule { get; set; }
        public virtual DbSet<TUserProp> TUserProp { get; set; }
        public virtual DbSet<tUsers20161129> tUsers20161129 { get; set; }
        public virtual DbSet<TWLoginRecord> TWLoginRecord { get; set; }
        public virtual DbSet<TZLoginRecord> TZLoginRecord { get; set; }
        public virtual DbSet<Web_AlmsDrawLog> Web_AlmsDrawLog { get; set; }
        public virtual DbSet<Web_Config> Web_Config { get; set; }
        public virtual DbSet<Web_CreateID> Web_CreateID { get; set; }
        public virtual DbSet<Web_FineryID> Web_FineryID { get; set; }
        public virtual DbSet<Web_Log> Web_Log { get; set; }
        public virtual DbSet<Web_Manage_Resource> Web_Manage_Resource { get; set; }
        public virtual DbSet<Web_Red20161029> Web_Red20161029 { get; set; }
        public virtual DbSet<Web_TGClearingRecord> Web_TGClearingRecord { get; set; }
        public virtual DbSet<Web_TGPayRecord> Web_TGPayRecord { get; set; }
        public virtual DbSet<wx_user_info> wx_user_info { get; set; }
    }
}
