//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_ProcErrorCollection
    {
        public long ID { get; set; }
        public int Number { get; set; }
        public int Severity { get; set; }
        public int State { get; set; }
        public string ProcName { get; set; }
        public int Line { get; set; }
        public string Msg { get; set; }
        public System.DateTime InputDate { get; set; }
    }
}
