//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBankDeposit
    {
        public int id { get; set; }
        public int Userid { get; set; }
        public long Money { get; set; }
        public string DepositID { get; set; }
        public string DepositPassWord { get; set; }
        public System.DateTime GreateTime { get; set; }
        public int CDSC { get; set; }
        public int State { get; set; }
        public Nullable<int> UsedUserID { get; set; }
    }
}
