//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBattleMatchTable
    {
        public int UserID { get; set; }
        public int RoomID { get; set; }
        public int NameID { get; set; }
        public long Point { get; set; }
        public long Money { get; set; }
        public long TaxCom { get; set; }
        public int Win { get; set; }
        public int Lost { get; set; }
        public int Mid { get; set; }
        public int Cut { get; set; }
        public int PlayTimeCount { get; set; }
        public int OnLineTimeCount { get; set; }
        public int MasterPower { get; set; }
        public int GamePower { get; set; }
        public int LogonTimes { get; set; }
        public System.DateTime LogonDate { get; set; }
        public int PlayTimes_T { get; set; }
        public int PlayCounts_T { get; set; }
    }
}
