//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChangeRecordUser
    {
        public int id { get; set; }
        public int RecordIndex { get; set; }
        public int UserIndex { get; set; }
        public int UserID { get; set; }
        public long SrcPoint { get; set; }
        public long SrcMoney { get; set; }
        public long ChangePoint { get; set; }
        public long ChangeMoney { get; set; }
        public long ChangeTax { get; set; }
        public int ReportStatus { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> iUseIngot { get; set; }
        public Nullable<int> iUseMoney { get; set; }
        public Nullable<int> iJiFen { get; set; }
        public Nullable<int> IsWinner { get; set; }
        public Nullable<int> IsDianPao { get; set; }
    }
}
