//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TChangeRecord
    {
        public int ID { get; set; }
        public int GameTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int RoomID { get; set; }
        public int DeskIndex { get; set; }
        public int Tax { get; set; }
        public Nullable<short> ModelType { get; set; }
        public Nullable<int> iQunNum { get; set; }
        public Nullable<int> riqi { get; set; }
        public Nullable<int> RoomCardNum { get; set; }
        public Nullable<int> iResultRule { get; set; }
        public Nullable<int> iFinishType { get; set; }
        public Nullable<int> iJuShu { get; set; }
        public Nullable<int> iFinishTime { get; set; }
    }
}
