//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContestInfo
    {
        public int ContestID { get; set; }
        public int SendTypeID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public long Chip { get; set; }
        public int LowCount { get; set; }
        public long LowChip { get; set; }
        public long EntryFee { get; set; }
        public int UpPeople { get; set; }
        public string Message { get; set; }
        public System.DateTime SendTime { get; set; }
        public string AwardContent { get; set; }
        public int TIMEOUT { get; set; }
        public bool ReportStatus { get; set; }
        public string MatchContent { get; set; }
    }
}
