//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContestRecord
    {
        public int ContestID { get; set; }
        public int ContestIndex { get; set; }
        public int UserID { get; set; }
        public long ChangeChip { get; set; }
        public int ChangePoint { get; set; }
        public long Chip { get; set; }
        public int DeskNo { get; set; }
        public int SitNo { get; set; }
        public int RoomID { get; set; }
        public System.DateTime Time { get; set; }
    }
}
