//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGameRoomTable
    {
        public int RoomID { get; set; }
        public string TableLock { get; set; }
        public string TableIPRule { get; set; }
        public string TableMatch { get; set; }
        public string TableUserNameRule { get; set; }
    }
}
