//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGameRoomBase
    {
        public int RoomID { get; set; }
        public int RoomRule { get; set; }
        public int DeskCount { get; set; }
        public int MaxPeople { get; set; }
        public int BasePoint { get; set; }
        public int LessPoint { get; set; }
        public int MoneyPoint { get; set; }
        public int Tax { get; set; }
        public int UserPower { get; set; }
        public int MaxLimite { get; set; }
        public int RunPublish { get; set; }
        public int t_change_m { get; set; }
        public int t_unit { get; set; }
        public int t_money { get; set; }
        public int day_moneytimes { get; set; }
        public int VipResever { get; set; }
        public int Tickets { get; set; }
        public int TaxType { get; set; }
        public int PlayTimes { get; set; }
        public int PlayTimesMoney { get; set; }
        public int PlayCounts_1 { get; set; }
        public int PlayCountsMoney_1 { get; set; }
        public int PlayCounts_2 { get; set; }
        public int PlayCountsMoney_2 { get; set; }
        public int PlayCounts_3 { get; set; }
        public int PlayCountsMoney_3 { get; set; }
        public long MaxPoint { get; set; }
        public int ContestID { get; set; }
        public long ExercisePoint { get; set; }
        public Nullable<int> RoomAdID { get; set; }
    }
}
