//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGameNameInfo
    {
        public int NameID { get; set; }
        public int KindID { get; set; }
        public string ComName { get; set; }
        public string ComProcess { get; set; }
        public int IDSort { get; set; }
        public byte Enable { get; set; }
        public long EveryDayRent { get; set; }
    }
}
