//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TGM_AwardType
    {
        public int SeriNo { get; set; }
        public int Gold { get; set; }
        public Nullable<int> PropID1 { get; set; }
        public Nullable<int> PropCount1 { get; set; }
        public Nullable<int> PropID2 { get; set; }
        public Nullable<int> PropCount2 { get; set; }
        public Nullable<int> PropID3 { get; set; }
        public Nullable<int> PropCount3 { get; set; }
        public Nullable<int> PropID4 { get; set; }
        public Nullable<int> PropCount4 { get; set; }
    }
}
