//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPropSale
    {
        public int SaleID { get; set; }
        public Nullable<int> ShopID { get; set; }
        public Nullable<int> PropID { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> VipLevel { get; set; }
        public Nullable<int> LotteriesPrice { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> SortID { get; set; }
        public Nullable<int> GameSortID { get; set; }
    }
}
