//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProp
    {
        public int id { get; set; }
        public int PropID { get; set; }
        public string PropName { get; set; }
        public Nullable<int> PropType { get; set; }
        public Nullable<int> ChildType { get; set; }
        public string Icon { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IsStack { get; set; }
        public Nullable<int> IsForever { get; set; }
        public Nullable<int> Expiration { get; set; }
        public Nullable<int> Sex { get; set; }
        public string Descript { get; set; }
        public Nullable<int> Method { get; set; }
        public Nullable<int> MethodParam1 { get; set; }
        public Nullable<int> MethodParam2 { get; set; }
    }
}
