//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPropBuyGive
    {
        public int id { get; set; }
        public int UserID { get; set; }
        public int TargetID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public int PropID { get; set; }
        public int PropCount { get; set; }
        public int Money { get; set; }
        public Nullable<int> Lotteries { get; set; }
        public Nullable<int> VipLevel { get; set; }
        public System.DateTime ActionTime { get; set; }
        public Nullable<int> ActionType { get; set; }
    }
}
