//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPropDefine
    {
        public int PropID { get; set; }
        public string PropName { get; set; }
        public int Price { get; set; }
        public int VipPrice { get; set; }
        public string Descript { get; set; }
        public int ActionAttribute { get; set; }
        public int ValueAttribute { get; set; }
        public int PropType { get; set; }
        public int LargessGold { get; set; }
    }
}
