//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TReceiveMoneyDefind
    {
        public int id { get; set; }
        public long ReceiveMoney { get; set; }
        public long MinMoney { get; set; }
        public int SpaceTime { get; set; }
        public Nullable<long> ReceiveIngot { get; set; }
    }
}
