//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRoomRecord
    {
        public int RoomID { get; set; }
        public int UserID { get; set; }
        public int ScrPoint { get; set; }
        public int ChangePoint { get; set; }
        public int ChangeMoney { get; set; }
        public int ChangeTax { get; set; }
        public int ResultPoint { get; set; }
        public int AutoPoint { get; set; }
        public int ChangeWin { get; set; }
        public int ChangeLost { get; set; }
        public int ChangeMid { get; set; }
        public int ChangeCut { get; set; }
        public int OnLineTime { get; set; }
    }
}
