//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUserInfo
    {
        public int UserID { get; set; }
        public int Member { get; set; }
        public int MatchMember { get; set; }
        public int Master { get; set; }
        public int GamePower { get; set; }
        public System.DateTime GPLimitTime { get; set; }
        public long WalletMoney { get; set; }
        public long BankMoney { get; set; }
        public int Fascination { get; set; }
        public int Viptime { get; set; }
        public int DoublePointTime { get; set; }
        public int ProtectTime { get; set; }
        public string LastLoginIP { get; set; }
        public int TimeIsMoney { get; set; }
        public int AllLoginTime { get; set; }
        public System.DateTime LastLoginTM { get; set; }
        public Nullable<long> TaxCom { get; set; }
        public string PhoneNum { get; set; }
        public string AdrNation { get; set; }
        public string AdrProvince { get; set; }
        public string AdrCity { get; set; }
        public string AdrZone { get; set; }
        public string OccuPation { get; set; }
        public int UserType { get; set; }
        public int DiamondTime { get; set; }
        public int LockMathine { get; set; }
        public string MathineCode { get; set; }
        public Nullable<int> OnlineMinutes { get; set; }
        public Nullable<System.DateTime> RoomLoginTime { get; set; }
        public Nullable<int> PresentCoinNum { get; set; }
        public Nullable<int> StatusByGM { get; set; }
        public Nullable<System.DateTime> StatusTime { get; set; }
        public Nullable<short> Trader { get; set; }
        public Nullable<int> KickUserTime { get; set; }
        public Nullable<int> AntiKickTime { get; set; }
        public string MyHardID { get; set; }
        public int AddFriendType { get; set; }
        public Nullable<int> EmailCount { get; set; }
        public long UserIngot { get; set; }
        public short ISCanTranMonBack { get; set; }
        public long TranMonBackValue { get; set; }
        public Nullable<int> VipLevel { get; set; }
        public Nullable<System.DateTime> VipeTime { get; set; }
        public Nullable<int> BakImgID { get; set; }
        public Nullable<System.DateTime> BakImgBTime { get; set; }
        public Nullable<int> HeadImgID { get; set; }
        public Nullable<System.DateTime> HeadImgBTime { get; set; }
    }
}
