//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUserCallGM
    {
        public int CallID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int RoomID { get; set; }
        public int NameID { get; set; }
        public int RoomType { get; set; }
        public int DeskStation { get; set; }
        public int DeskNumber { get; set; }
        public int ProblemType { get; set; }
        public System.DateTime callTime { get; set; }
        public string MessageReason { get; set; }
        public int GMID { get; set; }
        public string GMName { get; set; }
        public System.DateTime receiveTime { get; set; }
        public System.DateTime overTime { get; set; }
        public int TraiteRecord { get; set; }
    }
}
