//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUserProp
    {
        public int UserID { get; set; }
        public int PropID { get; set; }
        public int HoldCount { get; set; }
        public Nullable<System.DateTime> BuyTime { get; set; }
        public Nullable<System.DateTime> UserTime { get; set; }
    }
}
