//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TWLoginRecord
    {
        public int UserID { get; set; }
        public int WID { get; set; }
        public Nullable<int> DeskId { get; set; }
        public Nullable<int> RoomCardNum { get; set; }
    }
}
