//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Log
    {
        public int LogID { get; set; }
        public string LogUser { get; set; }
        public string LogIP { get; set; }
        public string OS { get; set; }
        public Nullable<byte> Result { get; set; }
        public string ErrorPas { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<bool> IsManage { get; set; }
    }
}
