//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_PointChangeLog
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string OrderID { get; set; }
        public int PayMoney { get; set; }
        public long ExchangeRate { get; set; }
        public Nullable<bool> InSuccess { get; set; }
        public Nullable<bool> PaySuccess { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> BackTime { get; set; }
        public string PayType { get; set; }
        public long BPoint { get; set; }
        public long APoint { get; set; }
        public int GameNameID { get; set; }
    }
}
