//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Analy_DateReport
    {
        public int ID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public int AvgOnline { get; set; }
        public int MaxOnline { get; set; }
        public int MinOnline { get; set; }
        public int LoginNum { get; set; }
        public int ActiveNum { get; set; }
        public int ActiveGameCount { get; set; }
        public int NewUserNum { get; set; }
        public int PayNum { get; set; }
        public int PayMoneyCount { get; set; }
        public int PayCount { get; set; }
        public int GameCount { get; set; }
        public int TaxCount { get; set; }
        public string AgencyName { get; set; }
        public int AgencyID { get; set; }
        public int RegNum { get; set; }
    }
}
