//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Agency
    {
        public int AgencyID { get; set; }
        public string AgencyName { get; set; }
        public string AgencyPassword { get; set; }
        public int ParentAgencyID { get; set; }
        public int LevelID { get; set; }
        public string TrueName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int PostalCode { get; set; }
        public string QQNum { get; set; }
        public string Email { get; set; }
        public string MobilPhone { get; set; }
        public string AccountNO { get; set; }
        public long Account { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public string PayorNo { get; set; }
        public string TenpayNo { get; set; }
        public decimal SpareValue { get; set; }
        public System.DateTime RegisterTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public byte IsTaboo { get; set; }
        public System.DateTime LastLoginDateTime { get; set; }
        public string LastLoginIP { get; set; }
        public string DomainUrl { get; set; }
        public string Remark { get; set; }
    }
}
