//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Tool_Action
    {
        public int ActionId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> SortId { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
