//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Activity
    {
        public int ActivityId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> BiSaiType { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string WeiXin { get; set; }
        public string QQ { get; set; }
        public string ZhengJian { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
