//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_TransfersAccount
    {
        public int TransferID { get; set; }
        public string Sender { get; set; }
        public string Receiver { get; set; }
        public long TransferMoney { get; set; }
        public Nullable<int> TransferFrequency { get; set; }
        public System.DateTime TransferTime { get; set; }
        public bool ReceiverType { get; set; }
        public string Remark { get; set; }
        public long SenderBFMoney { get; set; }
        public long SenderAFMoney { get; set; }
        public long ReceiverBFMoney { get; set; }
        public long ReceiverAFMoney { get; set; }
    }
}
