//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_RedGiftLog
    {
        public int LogId { get; set; }
        public Nullable<int> RandomNum { get; set; }
        public Nullable<int> GiftId { get; set; }
        public string Name { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string OpenId { get; set; }
        public string WXNickName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UseTime { get; set; }
        public string IP { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
