//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_AgentPay
    {
        public int PayId { get; set; }
        public string Num { get; set; }
        public string UserName { get; set; }
        public Nullable<int> PayMoney { get; set; }
        public string TypeInfo { get; set; }
        public string AgentName { get; set; }
        public Nullable<System.DateTime> BackTime { get; set; }
    }
}
