//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Clothes
    {
        public int ID { get; set; }
        public string LogName { get; set; }
        public long Price { get; set; }
        public long SendLotteries { get; set; }
        public int LogID { get; set; }
        public bool Sex { get; set; }
        public string Descript { get; set; }
        public int LargessGold { get; set; }
    }
}
