//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_IndexFlash
    {
        public int Flash_ID { get; set; }
        public string Title { get; set; }
        public string Picture { get; set; }
        public string URL { get; set; }
        public Nullable<int> Flash_Sort { get; set; }
        public Nullable<bool> Through { get; set; }
    }
}
