//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_TGPayRecord
    {
        public int RecordID { get; set; }
        public Nullable<int> PayUserID { get; set; }
        public Nullable<int> TGUserID { get; set; }
        public Nullable<int> PayMoney { get; set; }
        public Nullable<int> GetMoney { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
    }
}
