//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_GameInfo
    {
        public int Game_ID { get; set; }
        public string Game_Name { get; set; }
        public string Game_Info { get; set; }
        public string Game_Rule { get; set; }
        public string Down_address { get; set; }
        public Nullable<int> Down_Num { get; set; }
        public string FileSize { get; set; }
        public string Provice { get; set; }
        public string Area { get; set; }
        public Nullable<int> Game_TypeID { get; set; }
        public Nullable<bool> Through { get; set; }
        public string Image_URL { get; set; }
        public string Image_URL2 { get; set; }
        public Nullable<System.DateTime> UPdate_Time { get; set; }
        public Nullable<int> Game_Order { get; set; }
        public string Game_Process { get; set; }
        public string MatchTable { get; set; }
        public bool IsHot { get; set; }
        public string Game_SampleIntroduce { get; set; }
    }
}
