//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_TransAssetLog
    {
        public int TransferId { get; set; }
        public Nullable<int> SendUserId { get; set; }
        public string SendUserName { get; set; }
        public Nullable<int> WalletMoney { get; set; }
        public Nullable<int> BankMoney { get; set; }
        public Nullable<int> UserIngot { get; set; }
        public Nullable<int> ReceiveUserId { get; set; }
        public string ReceiveUserName { get; set; }
        public Nullable<int> ReceiveWalletMoneyBefor { get; set; }
        public Nullable<int> ReceiveWalletMoneyAfter { get; set; }
        public Nullable<int> ReceiveBankMoneyBefor { get; set; }
        public Nullable<int> ReceiveBankMoneyAfter { get; set; }
        public Nullable<int> ReceiveUserIngotBefor { get; set; }
        public Nullable<int> ReceiveUserIngotAfter { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
