//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_LotterAward
    {
        public int ID { get; set; }
        public string LotteryAwardName { get; set; }
        public int GoldRate { get; set; }
        public int SilverRate { get; set; }
        public int JadeRate { get; set; }
        public string PicName { get; set; }
        public Nullable<int> Number { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
