//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_msg
    {
        public int msgid { get; set; }
        public string msgname { get; set; }
        public string msgtitle { get; set; }
        public string msgsex { get; set; }
        public string tel { get; set; }
        public string fax { get; set; }
        public string msgface { get; set; }
        public string msgtext { get; set; }
        public string msgmail { get; set; }
        public string msghome { get; set; }
        public Nullable<System.DateTime> msgtime { get; set; }
        public string ip { get; set; }
        public string msgreplyname { get; set; }
        public string msgreply { get; set; }
        public Nullable<System.DateTime> msgreplytime { get; set; }
        public Nullable<int> msgprivate { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<int> msghit { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<bool> IsShow { get; set; }
    }
}
