//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Red
    {
        public int RedId { get; set; }
        public Nullable<int> Range { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> UseCount { get; set; }
        public Nullable<int> Type { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
