//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Agent
    {
        public int CateId { get; set; }
        public string CateName { get; set; }
        public int Lid { get; set; }
        public int Rid { get; set; }
        public int Depth { get; set; }
        public int Pid { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int Flag { get; set; }
        public string RealName { get; set; }
        public string Mobile { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string Address { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
