//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_FriendLink
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Link { get; set; }
        public int Type { get; set; }
        public string ImagePath { get; set; }
        public int OrderID { get; set; }
        public bool IsEnable { get; set; }
        public string ShortDesc { get; set; }
        public System.DateTime InputTime { get; set; }
    }
}
