//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_AlmsConfig
    {
        public int ID { get; set; }
        public int AlmsMoney { get; set; }
        public int AlmsDayCounts { get; set; }
        public string AlmsFirstNews { get; set; }
        public string AlmsSecondNews { get; set; }
        public string AlmsThirdNews { get; set; }
        public int AlmsLimitMoney { get; set; }
    }
}
