//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_ApplyVipRoom
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public string Email { get; set; }
        public string QQ { get; set; }
        public string Mobile { get; set; }
        public int ApplyGameNameID { get; set; }
        public System.DateTime OpenRoomDate { get; set; }
        public int AppleyDays { get; set; }
        public string RoomName { get; set; }
        public string RoomPwd { get; set; }
        public int DeskCount { get; set; }
        public int TaxType { get; set; }
        public int Tax { get; set; }
        public int MaxPeople { get; set; }
        public int BasePoint { get; set; }
        public int LessPoint { get; set; }
        public int MaxPoint { get; set; }
        public string RoomMsg { get; set; }
        public string RallWelcome { get; set; }
        public string Remark { get; set; }
        public int RoomID { get; set; }
        public short AuditStatus { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
