//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_SpreadPartner
    {
        public int Id { get; set; }
        public int PartnerId { get; set; }
        public string Password { get; set; }
        public int Level { get; set; }
        public string Mobile { get; set; }
        public string RealName { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public int ParentId { get; set; }
        public long IngotCount { get; set; }
        public string WeiXinOpenId { get; set; }
        public string WeiXinNickName { get; set; }
        public string WeiXinPhoto { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int PartnerCount { get; set; }
        public int Status { get; set; }
        public string Remark { get; set; }
    }
}
