//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_AgencyRMBCost
    {
        public int PayID { get; set; }
        public string TrueName { get; set; }
        public string Phone { get; set; }
        public string UserName { get; set; }
        public int PayMoney { get; set; }
        public byte PayType { get; set; }
        public string TypeInfo { get; set; }
        public string OrderID { get; set; }
        public System.DateTime AddTime { get; set; }
        public bool PaySuccess { get; set; }
        public Nullable<System.DateTime> BackTime { get; set; }
        public int MoneyFront { get; set; }
        public int MoneyAfter { get; set; }
    }
}
