//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_PlayerDayReport
    {
        public int RecordID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public int AgencyID { get; set; }
        public int MyPercent { get; set; }
        public long LwMoney { get; set; }
        public long SpareMoney { get; set; }
        public System.DateTime CountTime { get; set; }
        public int RoomName { get; set; }
        public int CountState { get; set; }
        public long WinMoney { get; set; }
        public long LoseMoney { get; set; }
        public int GameNameID { get; set; }
    }
}
