//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_IngotTransLog
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<long> TransBefore { get; set; }
        public Nullable<long> TransAfter { get; set; }
        public string UserNameZZ { get; set; }
        public Nullable<long> ZZ_TransBefore { get; set; }
        public Nullable<long> ZZ_TransAfter { get; set; }
        public Nullable<long> TransIngot { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<System.DateTime> TransTime { get; set; }
        public string IP { get; set; }
        public Nullable<bool> Success { get; set; }
    }
}
