//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_NewsData
    {
        public int News_ID { get; set; }
        public Nullable<byte> News_Type { get; set; }
        public string Title { get; set; }
        public string TitleColor { get; set; }
        public string Keywords { get; set; }
        public string News_From { get; set; }
        public string Author { get; set; }
        public string Issuer { get; set; }
        public string Content { get; set; }
        public string News_picture { get; set; }
        public Nullable<bool> Through { get; set; }
        public Nullable<bool> Recommendation { get; set; }
        public Nullable<bool> Istop { get; set; }
        public Nullable<System.DateTime> Issue_Time { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public Nullable<int> Hits { get; set; }
        public string News_Describe { get; set; }
        public string RedirectUrl { get; set; }
        public Nullable<int> Oid { get; set; }
    }
}
