//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_AwardLog
    {
        public int Log_ID { get; set; }
        public Nullable<int> Award_ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<long> Award_MoneyCost { get; set; }
        public Nullable<bool> IsCash { get; set; }
        public Nullable<System.DateTime> AwardTime { get; set; }
        public Nullable<int> Award_OnLineTime { get; set; }
        public string TrueName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string UserRemark { get; set; }
    }
}
