//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Manage_Popedom
    {
        public int Id { get; set; }
        public int AdminID { get; set; }
        public string ModelNo { get; set; }
        public int HasInsert { get; set; }
        public int HasUpdate { get; set; }
        public int HasDel { get; set; }
    }
}
