//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Award
    {
        public int Award_ID { get; set; }
        public string Award_Name { get; set; }
        public string Award_Info { get; set; }
        public string Award_Pic { get; set; }
        public Nullable<int> Award_Num { get; set; }
        public Nullable<long> Award_MoneyCost { get; set; }
        public Nullable<int> Award_MoneyGet { get; set; }
        public Nullable<int> Award_Type { get; set; }
        public Nullable<System.DateTime> Award_AddDate { get; set; }
        public Nullable<bool> Award_Hot { get; set; }
        public Nullable<int> Award_OnLineTime { get; set; }
        public Nullable<long> Award_NeedMoney { get; set; }
    }
}
