//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_manage_admin
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Purview { get; set; }
        public Nullable<byte> UserGroup { get; set; }
        public string LastLoginIP { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<System.DateTime> LastLogoutTime { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<int> AdminPurview_Article_T { get; set; }
        public Nullable<int> AdminPurview_Soft_T { get; set; }
        public Nullable<int> AdminPurview_Photo_T { get; set; }
        public string AdminPurview_Guest_T { get; set; }
        public string AdminPurview_Others_T { get; set; }
        public string RndPassword_T { get; set; }
    }
}
