//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_ArtifactLog
    {
        public int LogId { get; set; }
        public string AdminName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> BankMoney { get; set; }
        public Nullable<int> WalletMoney { get; set; }
        public Nullable<int> SumMoney { get; set; }
        public Nullable<int> BalanceMoeny { get; set; }
        public Nullable<long> TranMoeny { get; set; }
        public Nullable<long> DestMoney { get; set; }
        public Nullable<long> PayMoney { get; set; }
        public Nullable<long> PointMoney { get; set; }
        public Nullable<int> Type { get; set; }
        public string Ip { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
