//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_EveryoneSpreadRebate
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public Nullable<long> OneUseCount { get; set; }
        public Nullable<int> OnePercent { get; set; }
        public Nullable<long> OneGetCount { get; set; }
        public Nullable<long> TwoUseCount { get; set; }
        public Nullable<int> TwoPercent { get; set; }
        public Nullable<long> TwoGetCount { get; set; }
        public Nullable<int> GetStatus { get; set; }
        public Nullable<System.DateTime> GetTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
