//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Card
    {
        public int ID { get; set; }
        public Nullable<int> Users_ids { get; set; }
        public string num { get; set; }
        public string pwd { get; set; }
        public Nullable<int> jine { get; set; }
        public string player { get; set; }
        public Nullable<System.DateTime> tm { get; set; }
        public string ip { get; set; }
        public Nullable<bool> pay { get; set; }
        public Nullable<int> types { get; set; }
        public Nullable<System.DateTime> addtime { get; set; }
        public long BMoney { get; set; }
        public long AMoney { get; set; }
        public Nullable<bool> ToPoint { get; set; }
        public Nullable<int> Tag { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
