//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Config
    {
        public int ID { get; set; }
        public string BadUserName { get; set; }
        public string BadNickName { get; set; }
        public Nullable<int> MoneyToViptime { get; set; }
        public Nullable<int> MoneyToViptimeDay { get; set; }
        public Nullable<int> MoneyToViptimeWeek { get; set; }
        public Nullable<int> MoneyToViptimeMonth { get; set; }
        public Nullable<int> MoneyToViptimeHYear { get; set; }
        public Nullable<int> MoneyToViptimeYear { get; set; }
        public Nullable<int> UserobligateMoney { get; set; }
        public Nullable<long> TransferLessMoney { get; set; }
        public Nullable<long> TransferLessAllMoney { get; set; }
        public Nullable<int> TransferTax { get; set; }
        public Nullable<int> TransferMultiple { get; set; }
        public Nullable<int> MaxTransTax { get; set; }
        public Nullable<int> Con_ValidDay { get; set; }
        public Nullable<int> Con_OnlineTime { get; set; }
        public Nullable<int> Con_ValidUserAddMoney { get; set; }
        public Nullable<int> Con_CardInPercent { get; set; }
        public Nullable<int> Con_GetMoneyPercent { get; set; }
        public Nullable<int> Con_RegMoney { get; set; }
        public Nullable<int> Con_ValidUserMoney { get; set; }
        public Nullable<int> Con_MinClearingMoney { get; set; }
        public Nullable<int> Con_MoneyChangeRate { get; set; }
        public Nullable<int> RegWallet { get; set; }
        public string IPDisabled { get; set; }
        public int ReRegTimeSpan { get; set; }
        public string YeepayMsgInfo { get; set; }
        public int VipTransferTax { get; set; }
        public int Yeepay_Rate_NetBank { get; set; }
        public int Yeepay_Rate_Junnet { get; set; }
        public int Yeepay_Rate_Szx { get; set; }
        public int Yeepay_Rate_Unicom { get; set; }
        public int Yeepay_Rate_YPCard { get; set; }
        public int FreeCardCount { get; set; }
        public Nullable<int> MaxTransUserMoney { get; set; }
        public Nullable<System.DateTime> StartPresent { get; set; }
        public Nullable<System.DateTime> EndPresent { get; set; }
        public Nullable<int> CoinNum { get; set; }
        public Nullable<int> TimeLength { get; set; }
        public string GameNameID { get; set; }
        public string TG_GameNameID { get; set; }
        public string SpecialUser { get; set; }
        public bool MRView { get; set; }
        public string FineryIDRegex { get; set; }
        public string FineryIDDefaultPrice { get; set; }
        public Nullable<long> MaxPayMoney { get; set; }
        public int CreateBankTax { get; set; }
        public int BankVersion { get; set; }
        public int RobotRank { get; set; }
        public Nullable<int> UserMaxPayMoney { get; set; }
        public Nullable<int> SameIPRegCount { get; set; }
        public Nullable<int> SameCardNoRegCount { get; set; }
        public Nullable<int> LastLoginGameCount { get; set; }
        public Nullable<long> Con_PointChangeRate { get; set; }
        public Nullable<int> BankRate { get; set; }
        public Nullable<bool> IsDisplayHomeGameAD { get; set; }
        public Nullable<bool> IsDisplayHomeMoneyInfo { get; set; }
        public int Ingot_MoneyChangeRate { get; set; }
        public int Con_IngotChangeRate { get; set; }
        public int IsPayToIngot { get; set; }
        public int IsIngotToProp { get; set; }
        public int IsIngotToGold { get; set; }
        public int PartnerToCommonTax { get; set; }
        public int PartnerToPartnerTax { get; set; }
        public int CommToPartnerTax { get; set; }
        public int PToCReturnTax { get; set; }
        public int PToPReturnTax { get; set; }
        public long TranMonBackLimit { get; set; }
        public Nullable<int> BindPhoneMoney { get; set; }
        public Nullable<int> BindWeiXinMoney { get; set; }
        public Nullable<int> IsNeedPhone { get; set; }
        public Nullable<long> UpperLimitMoney { get; set; }
    }
}
