//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_UserAlbum
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int ColumnID { get; set; }
        public string PicName { get; set; }
        public string PicPath { get; set; }
        public string PicDescription { get; set; }
        public int ShortNum { get; set; }
        public string Enable { get; set; }
        public System.DateTime InputTime { get; set; }
    }
}
