//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_SMSLog
    {
        public int LogID { get; set; }
        public string Operater { get; set; }
        public string SMScontent { get; set; }
        public Nullable<int> SMStype { get; set; }
        public string ReturnStr { get; set; }
        public string MobileNo { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
