//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_GameMain
    {
        public short Main_ID { get; set; }
        public string Main_Info { get; set; }
        public string sMain_Info { get; set; }
        public string Main_Copy { get; set; }
        public string sMain_Copy { get; set; }
        public string Main_use { get; set; }
        public string sMain_use { get; set; }
        public Nullable<System.DateTime> Update_Time { get; set; }
        public string Down_saddress { get; set; }
        public string Down_address { get; set; }
        public Nullable<int> Down_num { get; set; }
        public string sFileSize { get; set; }
        public string FileSize { get; set; }
        public string Image_URL { get; set; }
        public string sImage_URL { get; set; }
    }
}
