//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Artifact
    {
        public int ArtifactId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> WinRate { get; set; }
        public Nullable<long> PresetSize { get; set; }
        public Nullable<long> CurrentSize { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    }
}
