//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_AdminEmail
    {
        public int MsgID { get; set; }
        public string MsgContent { get; set; }
        public System.DateTime SendTime { get; set; }
        public string AdminName { get; set; }
        public int UserID { get; set; }
        public int IsSend { get; set; }
        public int IsToAll { get; set; }
        public int IsMarquee { get; set; }
        public string MsgWebContent { get; set; }
        public Nullable<int> Type { get; set; }
        public string MsgTitle { get; set; }
        public Nullable<int> IsHallMarquee { get; set; }
        public Nullable<int> LoopTime { get; set; }
        public Nullable<int> MsgTimes { get; set; }
    }
}
