//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Web_Exchange
    {
        public long ExID { get; set; }
        public int UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime AddTime { get; set; }
        public int ApplyMoney { get; set; }
        public int ApplyState { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public string BankName { get; set; }
        public string BankAddress { get; set; }
        public Nullable<System.DateTime> DisposeTime { get; set; }
        public string DisposeDesc { get; set; }
        public int AccountType { get; set; }
        public int UserType { get; set; }
    }
}
