//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wx_user_info
    {
        public int id { get; set; }
        public string unionid { get; set; }
        public string openid { get; set; }
        public string nickname { get; set; }
        public string headimgurl { get; set; }
        public string access_token { get; set; }
        public string refresh_token { get; set; }
        public string scope { get; set; }
        public Nullable<int> expires_in { get; set; }
        public string create_time { get; set; }
        public Nullable<int> sex { get; set; }
        public string language { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public string privilege { get; set; }
    }
}
